state_level_normal_prompts = [
    '{}',
    'normal {}',
    'healthy {}',
    '{} without abnormality',
    '{} without pathology',
    '{} without acute findings',
    '{} with clear lung fields',
    '{} within normal limits',
]

state_level_abnormal_prompts = [
    'abnormal {}',
    '{} with lung disease',
    '{} with opacity',
    '{} with cardiomegaly',
    '{} with pulmonary atelectasis',
    '{} with calcinosis',
    '{} with calcified granuloma',
    '{} with cicatrix',
    '{} with pleural effusion',
    '{} with atherosclerosis',
    '{} with granulomatous disease',
    '{} with density',
    '{} with deformity',
    '{} with airspace disease',
    '{} with nodule',
    '{} with scoliosis',
    '{} with fractures',
    '{} with spondylosis',
    '{} with osteophyte',
    '{} with pulmonary congestion',
    '{} with emphysema',
    '{} with granuloma',
    '{} with infiltrate',
    '{} with thickening',
    '{} with pulmonary disease chronic obstructive',
    '{} with pulmonary edema',
    '{} with hernia',
    '{} with pneumonia',
    '{} with pulmonary emphysema',
    '{} with consolidation',
    '{} with kyphosis',
    '{} with pneumothorax',
    '{} with pulmonary fibrosis',
    '{} with lung diseases interstitial',
    '{} with mass',
    '{} with volume loss',
    '{} with heart failure',
    '{} with hypertension pulmonary',
    '{} with pericardial effusion',
    '{} with tuberculosis',
    '{} with bullous emphysema',
    '{} with sarcoidosis',
    '{} with cavitation',
    '{} with bronchiectasis',
    '{} with cystic fibrosis',
    '{} with pathology',
    '{} with abnormal findings',
]

state_level_normality_specific_prompts = [
    # needed to be designed category by category
]

state_level_abnormality_specific_prompts = [
    '{} with {} abnormality',
    '{} with {} pathology',
    '{} with {} finding',
]

template_level_prompts = [
    'a chest x-ray of a {}',
    'a chest x-ray of the {}',
    'a frontal chest x-ray of a {}',
    'a frontal chest x-ray of the {}',
    'a lateral chest x-ray of a {}',
    'a lateral chest x-ray of the {}',
    'a chest radiograph of a {}',
    'a chest radiograph of the {}',
    'a chest x-ray showing {}',
    'a chest x-ray of a {} for visual inspection',
    'a chest x-ray of a {} for anomaly detection',
    'a medical image of a {}',
    'a medical image of the {}',
]
